# Información general
site_name: 'Redes con software libre'
site_description: 'Redes de datos con software libre'
site_author: 'Raul Jesus Lopez'
site_url: http://www.redes.rauljesus.com

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/redes'

# Copyright
#copyright: '2017 - Raul Jesus Lopez'

# Tema
theme: null
theme_dir: 'themes/material'

# Opciones
extra:
  palette:
    primary: 'deep purple'
    accent: 'purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
#    - type: 'github'
#      link: 'https://github.com/la9una'
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'
#    - type: 'facebook'
#      link: 'https://www.facebook.com/rauljesuslopez'

# Google Analytics
google_analytics:
  - 'UA-98408177-1'
  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Extras
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Páginas
pages: 
- Inicio: 'index.md'
- Resolución de nombres: 
    - El archivo hosts: 'resolucionNombresHosts.md'
- LAMP:
    - ¿Qué es?: 'lamp/queEs.md'
    - Instalación: 'lamp/instalacion.md'
    - Gestión básica: 'lamp/gestionBasica.md'
    - Web de usuario: 'lamp/userdir.md'
    - Hosts virtuales: 'lamp/virtualHosts.md'
    - Ejercicios prácticos: 'lamp/ejercicios.md'

