site_name: 'Redes de datos'
site_description: 'Redes con Software Libre'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.com
repo_url: https://github.com/la9una/redes
theme: null
theme_dir: themes/material
